# Elasticsearch versions
# NOTE (alextricity25):
# The elasticsearch version variables needs to be available to the repo_build role
# due to the way it builds out the distro packages dataset. Distro packages within
# a role are indexed using their raw form(jinja is not rendered). The repo_build
# role then attempts to render these datasets, and will fail if it cannot resolve
# a variable. Putting these variables in here ensures the repo_build
# role can interpolate the variables correctly.
elasticsearch_version: 2.4.1
elasticsearch_reindex_version: 1.7.5
es_instance_name: "openstack"
es_config:
  node.name: "{{ container_name }}"
  cluster.name: "openstack"
  http.port: 9200
  transport.tcp.port: 9300
  node.data: true
  node.master: true
  network.host: "127.0.0.1"
  discovery.type: "single-node"
